name: Deploy to server

on: push

jobs: 
  first_job: 
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo Primero"

  second_job: 
    runs-on: ubuntu-latest

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo Segundo"