name: Deploy to server

on: push

jobs: 
  first_job: 
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    env:
      GITHUB_TOKEN: Test
    steps:
      - name: Work directory
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT

      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"

  second_job: 
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: first_job
    runs-on: ubuntu-latest

    env: 
      SALIDA: ${{ needs.first_job.outputs.salida}}

    steps:
      - name: Hola Mundo
        run: echo "Hola Mundo - Variable Global $SALIDA"
      - name: Hola Mundo Corchetes
        run: echo "Hola Mundo - Variable Global ${SALIDA}"
        