name: Deploy to server

on: push

jobs: 
  first_job: 
    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        message: [ "Msg1", "Msg2", "Msg3"]

    steps: 
      - name: Print message
        run: echo ${{ matrix.message }}

